feat(cli): add explorer
omni-network/omni pull request #1152
Opened 2024-05-31 10:04 UTC by idea404

add explorer to cli devnet

task: https://app.asana.com/0/1206208509925075/1207138429056645/f

2024-05-31 10:06 UTC, pavelnikolov approved these changes

2024-05-31 10:23 UTC, pavelnikolov approved these changes

2024-05-31 12:53 UTC, corverroos requested changes
explorer-ui is not a go program... Not sure we can use goreleaser to build it. Does this actually work?

2024-05-31 13:18 UTC, pavelnikolov commented on .github/workflows/release-official.yml
> +            omniops/explorer-ui:${GITHUB_REF##*/}  # This adds the tag (e.g., v0.1.8)
Does this work with the docker/build-push-action? I thought that only `,` sperator works 🤔

2024-05-31 15:11 UTC, idea404 commented
This PR will require updating the `clicommand.yml` to include the Explorer UI Docker images if https://github.com/omni-network/omni/pull/1151 is merged first

2024-06-04 13:55 UTC, corverroos commented on cli/cmd/devnet.go
> +	defCfg.GraphQLURL = "http://explorer_graphql:8080/query"
rather add this as the "default" GraphQLURL [here](https://github.com/omni-network/omni/blob/main/e2e/app/definition.go#L59).

2024-06-04 16:06 UTC, merged