feat(monitor/xfeemngr): manage fee params for chain not in network
omni-network/omni pull request #1706
Opened 2024-08-13 23:20 UTC by kevinhalliday

Support management of onchain fee params for a chain not in the network.

Testnet sepolia chains post tx data to sepolia. Their xcall fees should therefore 
be calculated using sepolia gas prices. Sepolia is not in the omega network, but we
need to manage it's fee params on chain.

issue: none

2024-08-13 23:41 UTC, kevinhalliday commented
Currently not setting fee params for chains not in network on deploy. So we'd need to wait for xfeemngr to set it before sending xcalls to sepolia l2s. TBD if this would be an issue for e2e deploy, it may cause ping pong starts to fail. Staging deploy will tell us. If it's an issue we can add. Maybe worth adding anyways

2024-08-14 00:15 UTC, kevinhalliday commented on lib/evmchain/evmchain.go
> -	IDMockL1Slow: {
We weren't using slow l1 anywhere so i removed

2024-08-14 10:07 UTC, corverroos requested changes
Just blocking this until omega either deployed or until we decide to delay omega until this is properly tested and confirmed on staging.

2024-08-14 13:04 UTC, corverroos approved these changes

2024-08-21 14:09 UTC, merged