feat(e2s): add RoleTester service account key for mainnet part 1
omni-network/omni pull request #2352
Opened 2024-11-01 11:20 UTC by kc1116

This PR adds a RoleTester key for mainnet so that we can submit xmsgs to mainnet via a script. Currently the key generation tool assumes that all keys being created for a application service. This PR adds the `Service` key type so that we can generate keys for utility purposes.

```
 go run e2e/main.go key-create -f e2e/manifests/mainnet.toml --name=tester --type=service
```
We generated a new _service_ key for mainnet and mapped it to the RoleTester. Now we can access this key in the e2e app the same way we access RoleTester for other networks.

issue: #2275

2024-11-01 11:36 UTC, kc1116 commented
Currently the key generation tool assumes that all keys being created for a application service. This PR adds the `Service` key type so that we can generate keys for utility purposes.

```
 go run e2e/main.go key-create -f e2e/manifests/mainnet.toml --name=tester --type=service
```
We generated a new _service_ key for mainnet and mapped it to the RoleTester. Now we can access this key in the e2e app the same way we access RoleTester for other networks.

2024-11-01 11:52 UTC, chmllr approved these changes
Code LGTM, can't validate the logic yet.

2024-11-01 12:59 UTC, sideninja commented on e2e/app/eoa/static.go
> +		secret("0x84aC7eeC1e035Fa13a7DEBD5f6da69B82CBDC5B5", RoleTester),
wouldn't it be better for this account to be remote type, managed by Fireblocks?

2024-11-01 13:28 UTC, corverroos commented on e2e/app/key/key.go
> +	Service      Type = "service"
no need for a new type, this is an eoa

2024-11-01 13:29 UTC, corverroos commented on e2e/manifests/mainnet.toml
> +[keys.tester]
don't think this is the way to go, it deplicates whatever is in the eoa package. Follow the same patterns as relayer and monitor keys.

2024-11-01 13:30 UTC, corverroos requested changes
Blocking review since christiaan aproved and this is the way to go

2024-11-04 11:58 UTC, kc1116 commented
Did not have to do.

2024-11-04 11:58 UTC, closed without merging