feat(monitor): Add xcall loadgen to the monitor app
omni-network/omni pull request #2723
Opened 2024-12-19 21:24 UTC by kc1116

This PR adds xcall load generation to the monitor app. 

issue: #2275

2024-12-23 19:23 UTC, kevinhalliday commented on monitor/app/testdata/default_monitor.toml
> +
`xcaller` is part of loadgen, so let's make it part of loadgen config

2024-12-23 19:23 UTC, kevinhalliday commented on monitor/loadgen/loadgen.go
> +
This `Start` function has a lot of stuff in it now. First half about loadgening validator updates. Second part about loadgening xcalls. Maybe put both in their own function

2024-12-23 19:23 UTC, kevinhalliday commented on e2e/manifests/devnet1.toml
> +mock_l2 = "mock_l1"
Some thoughts on config.

- let's make it clear these are part of loadgen config
- we use chain names, not chain ids.
- do we have a reason for specifying which xcalls to to make xcalls from / to? if not, let's just do all of them. until we have a reason for more granular control

```toml
[loadgen.xcalls]
enabled = true
```

if we do have a need to specify, I think pairs are limitting. for ex, we could not loadtest xcalls on all streams by  configuring pairs (at least, not as written). What about just specifying source and destination chains with a regex

```toml
[loadgen.xcall]
from = "mock_l1|mock_l2"
to = "*"
```

2025-01-06 10:45 UTC, corverroos requested changes

2025-01-06 10:45 UTC, corverroos commented on e2e/types/manifest.go
> +	XCallerEnabled bool `toml:"xcaller_enabled"`
lets follow the existing loadgen pattern, "Validator self-delegation" is simply enabled by presence of the key. Also, avoid complex configuration options in v1, simply hardcode the chain pairs in `monitor`. lessismore.

2025-01-06 10:45 UTC, corverroos commented on lib/xchain/connect/connect.go
> +func (c Connector) GetPortal(chainID uint64, backend bind.ContractBackend) (*bindings.OmniPortal, error) {
xconnector isn't used in monitor, it is only used in scripts, lets keep it that way. please remove this.

2025-01-13 14:40 UTC, kc1116 commented on monitor/loadgen/loadgen.go
> +
https://github.com/omni-network/omni/pull/2723/commits/58dd7e6400ffb7afc51b6e698a1c3c91d43b1709

2025-01-13 15:16 UTC, corverroos commented on monitor/loadgen/xcall.go
> +	gasLimit := uint64(100_000)
or even better, use `portal.XMsgMinGasLimit`

2025-01-13 15:16 UTC, corverroos commented on monitor/loadgen/xcall.go
> +	var data []byte
nil: `nilData`

2025-01-13 15:16 UTC, corverroos commented on monitor/loadgen/xcall.go
> +	fromChain, dstChain := getChainPair()
nit: we commonly use `srcChain`, not `fromChain`

2025-01-13 15:16 UTC, corverroos commented on monitor/loadgen/xcall.go
> +	log.Debug(ctx, fmt.Sprintf("xcall made %s -> %s %s", fromChain.Name, dstChain.Name, tx.Hash()))
avoid %s or %v in logging, use structured log attributes rather

2025-01-13 15:16 UTC, corverroos commented on monitor/loadgen/xcall.go
> +	tx, err := fromPortal.Xcall(txOpts, dstChain.ID, uint8(xchain.ConfLatest), to, data, gasLimit)
you have to waitmined the tx

2025-01-13 18:58 UTC, kc1116 commented on monitor/loadgen/loadgen.go
> +	err := startSelfDelegationLoadgen(ctx, network, ethClients, cfg)
https://github.com/omni-network/omni/pull/2723/commits/88aaaaa02b7cc355fc943ad892c3dc8e5e6f1fce

2025-01-13 18:58 UTC, kc1116 commented on monitor/loadgen/loadgen.go
> +		return errors.Wrap(err, "failed to get RoleXCaller priv key exiting xcall loadgen")
https://github.com/omni-network/omni/pull/2723/commits/ea9589188e9e0e7a579c01ff54925afc4c60e602

2025-01-13 18:58 UTC, kc1116 commented on monitor/loadgen/loadgen.go
> +	}
https://github.com/omni-network/omni/pull/2723/commits/d6db3c5acb73dae2870d752dd4aee8959e410ec0

2025-01-13 18:58 UTC, kc1116 commented on monitor/loadgen/xcall.go
> +type XCallConfig struct {
https://github.com/omni-network/omni/pull/2723/commits/c14f5325ac6a1a054b3917a640d5248bfcb7f578

2025-01-13 18:59 UTC, kc1116 commented on monitor/loadgen/xcall.go
> +func xCallForever(ctx context.Context, cfg *XCallConfig) {
https://github.com/omni-network/omni/pull/2723/commits/6cb7a34294771a04bb7b84bb074d4290dfec33e1

2025-01-13 18:59 UTC, kc1116 commented on monitor/loadgen/xcall.go
> +	// tick immediately
https://github.com/omni-network/omni/pull/2723/commits/37390edeec7578c0119309a7b10b720b1060d9cc

2025-01-13 18:59 UTC, kc1116 commented on monitor/loadgen/xcall.go
> +func xCall(ctx context.Context, cfg *XCallConfig, getChainPair func() (from netconf.Chain, to netconf.Chain)) error {
https://github.com/omni-network/omni/pull/2723/commits/fb42b3861868fdbf333f5db2a1a5e2f4ccd33d87

2025-01-13 18:59 UTC, kc1116 commented on monitor/loadgen/xcall.go
> +	gasLimit := uint64(100_000)
https://github.com/omni-network/omni/pull/2723/commits/b939ced126c9f022bf8ba4d2896d172737a97bb5

2025-01-13 18:59 UTC, kc1116 commented on monitor/loadgen/xcall.go
> +	fee, err := fromPortal.FeeFor(&bind.CallOpts{}, dstChain.ID, data, gasLimit)
https://github.com/omni-network/omni/pull/2723/commits/20ebdf2615c49eff8375cbf284c5832f68e870bc

2025-01-13 19:00 UTC, kc1116 commented on monitor/loadgen/xcall.go
> +	dead = "0x000000000000000000000000000000000000dead"
https://github.com/omni-network/omni/pull/2723/commits/3cea5d1e4a30aaf4dd0282707760899da91c711e

2025-01-13 19:00 UTC, kc1116 commented on monitor/loadgen/xcall.go
> +	fromChain, dstChain := getChainPair()
https://github.com/omni-network/omni/pull/2723/commits/d78c48c1ea9954e550af3cb65161f4a1e254df88

2025-01-13 19:00 UTC, kc1116 commented on monitor/loadgen/xcall.go
> +	log.Debug(ctx, fmt.Sprintf("xcall made %s -> %s %s", fromChain.Name, dstChain.Name, tx.Hash()))
https://github.com/omni-network/omni/pull/2723/commits/21f8d15443640dce3209ee379fe9ae5fbd3d32e6

2025-01-13 19:00 UTC, kc1116 commented on monitor/loadgen/xcall.go
> +	tx, err := fromPortal.Xcall(txOpts, dstChain.ID, uint8(xchain.ConfLatest), to, data, gasLimit)
https://github.com/omni-network/omni/pull/2723/commits/2524d441827708d4f8f4d9101aa1d944d6d5f724

2025-01-13 19:01 UTC, kc1116 commented on e2e/app/definition.go
> +	endpoints[def.Testnet.Network.Static().OmniConsensusChain().Name] = fmt.Sprintf("http://%s", node.AddressRPC())
https://github.com/omni-network/omni/pull/2723/commits/b0ca8e5317fe148703b1d081204481e3b530f33e

2025-01-13 19:01 UTC, kc1116 commented on monitor/loadgen/loadgen.go
> +	xCallerPK, err := eoa.PrivateKey(ctx, network.ID, eoa.RoleXCaller)
https://github.com/omni-network/omni/pull/2723/commits/99ee1ffb0f153fcac922c9e2d5dc246a40e71471

2025-01-14 05:35 UTC, corverroos approved these changes
LGTM

2025-01-14 05:35 UTC, corverroos commented on monitor/loadgen/xcall.go
> +	fromPortal, err := getPortal(ctx, cfg.NetworkID, srcChain.ID, cfg.Backends)
nit: rename `srcPortal`

2025-01-14 14:34 UTC, kc1116 commented on monitor/loadgen/xcall.go
> +	fromPortal, err := getPortal(ctx, cfg.NetworkID, srcChain.ID, cfg.Backends)
https://github.com/omni-network/omni/pull/2723/commits/0b76724d969739167ae746e2b7585a8f93e6df53

2025-01-14 16:54 UTC, merged