chore(ci): add docs pr and deploy ci
omni-network/omni pull request #305
Opened 2024-02-15 19:49 UTC by idea404

This PR introduces:

- the `site/` directory in `./docs` (with `.gitkeep`)
- A workflow (`ci-pr-docs.yml`) for deploying preview PRs using the vercel CLI and a github action for commenting the URL of this deployed version
- A workflow (`ci-docs.yml`) for deploying any merges to `main` that have updates to `./docs/site` to the production vercel environment

task: none or https://app.asana.com/0/1206208509925075/1206566996089561

2024-02-15 20:14 UTC, ttarsi reviewed
looks good, let's just test it

2024-02-15 20:14 UTC, ttarsi commented on .github/workflows/ci-pr-docs.yml
> +      - idea404/docusaurus-docs
can we give this a test run by opening a PR to the `idea404/docusaurus-docs` branch, and seeing if the deployment & comment works?

2024-02-15 20:14 UTC, ttarsi commented on .github/workflows/ci-pr-docs.yml
> +      - idea404/docusaurus-docs
alternatively, we could say on push: `ideo404/ci-docs` so that it should populate here directly

2024-02-15 22:27 UTC, pavelnikolov commented on .github/workflows/ci-docs.yml
> +      - idea404/docusaurus-docs # TODO: change this to main once docusaurus is merged
Change this before merging

2024-02-15 22:32 UTC, pavelnikolov requested changes

2024-02-15 22:32 UTC, pavelnikolov commented on .github/workflows/ci-pr-docs.yml
> +        run: echo "::set-output name=deployment_url::$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
`::set-output` is deprecated. Use the `$GITHUB_OUTPUT` variable instead. 
```suggestion
        run: echo "deployment_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
```

2024-02-16 11:28 UTC, idea404 commented on .github/workflows/ci-docs.yml
> +      - idea404/docusaurus-docs # TODO: change this to main once docusaurus is merged
Added todo for this just now 👍

2024-02-16 14:11 UTC, idea404 commented
Thanks for the careful comments guys @pavelnikolov @ttarsi! 

I have edited both scripts and have them run against this branch. Both workflows ([deploy](https://github.com/omni-network/omni/actions/runs/7929909800/job/21651094162?pr=305) and [preview](https://github.com/omni-network/omni/actions/runs/7929909793/job/21651093941?pr=305)) trigger and go through the initial setup steps until they fail at the build step since `./docs/site` is empty now. 

I have [deployed both workflows in a fork repo of this monorepo](https://github.com/idea404/omni/commit/067625c31d8c3f3977daef2185e933c1f42a93ba) with the following outcomes: 
- `deploy` - [deployed](https://github.com/idea404/omni/actions/runs/7931128256/job/21654710218) a new [live version of the docs](https://omni-sandy.vercel.app/docs/next/home) after a [docs PR merge](https://github.com/idea404/omni/commit/8bdaa069cb79b7cdbc1f9c9943e603f219fabcdb)
- `preview` - builds and deploys a preview using vercel and comments on the PR using the URL, [see example](https://github.com/idea404/omni/pull/14)

2024-02-16 14:13 UTC, pavelnikolov approved these changes

2024-02-16 19:38 UTC, merged