chore(eoa): refactor accounts
omni-network/omni pull request #873
Opened 2024-04-17 14:15 UTC by Lazar955

moves accounts in central place in EOA

task: none

2024-04-17 15:24 UTC, idea404 approved these changes

2024-04-17 19:57 UTC, kevinhalliday approved these changes

2024-04-17 19:57 UTC, kevinhalliday commented on e2e/app/eoa/static.go
> +			TargetBalance: big.NewInt(10),
I don't think create3 deployers need this much - they only ever do one deployment

2024-04-18 07:14 UTC, corverroos requested changes

2024-04-18 07:14 UTC, corverroos commented on e2e/app/eoa/eoa.go
> +	if network == netconf.Devnet {
this should be based on type:
- if type == wellknown, return privkey
- if type == remote, return error
- if type == secret, download

2024-04-18 07:14 UTC, corverroos commented on e2e/app/eoa/eoa.go
> +type ChainSelector func(netconf.Network) []netconf.Chain
this type and impls below can be unexported

2024-04-18 07:14 UTC, corverroos commented on e2e/app/eoa/static.go
> +			MinBalance:    big.NewInt(10),
balancers are in wei, so this is 10 wei, which is basically 0. I suggest you create some globals:
```
var (
  ether1 = new(big.Int).Mul(big.NewInt(1),big.NewInt(params.Ether)
  ether5 = new(big.Int).Mul(big.NewInt(5),big.NewInt(params.Ether) 
  ether10 ...
  etc
)
```

2024-04-18 07:14 UTC, corverroos commented on e2e/app/eoa/static.go
> +			Address:       crypto.PubkeyToAddress((anvil.DevPrivateKey5()).PublicKey),
anvil package has address vars, no need to convert

2024-04-18 07:14 UTC, corverroos commented on e2e/app/eoa/eoa.go
> +func addr(hex string) common.Address {
rather use common.HexToAddress(hex) directly, this abbreviation isn't super clear

2024-04-18 07:14 UTC, corverroos commented on e2e/app/eoa/static.go
> +			MinBalance:    big.NewInt(10),
Suggest also to group threshold balances into 3 groups maybe:
```
var (
  minBalanceSmall = gwei100
  targetBalanceSmall = gwei500
  
  minBalanceMedium = ether1
  targetBalanceMedium = ether5
  
  minBalanceLarge = ether10
  targetBalanceLarge = ether100 
)
```

then map accounts to one of these. Please confirm these balances in slack thread with the team

2024-04-18 07:14 UTC, corverroos commented on e2e/cmd/cmd.go
> +		eoaRole := eoa.Role(cfg.Name)
we should very type==secret and role==valid

2024-04-18 07:14 UTC, corverroos commented on lib/contracts/portal/deploy.go
> +		Create3Salt:    eoa.PortalSalt(netconf.Mainnet),
PortalSalt is not a eoa thing, it is a contract thing, move it back pls.

2024-04-18 07:14 UTC, corverroos commented on lib/contracts/portal/deploy.go
> +		return eoa.MainnetPortal(), true
portals are not eoa, they are contracts, move it back pls

2024-04-18 07:14 UTC, corverroos commented on lib/contracts/portal/deploy.go
> +		Create3Factory: eoa.DevnetCreate3Factory(),
create3factory is a contract, not a eoa, move it back pls

2024-04-18 07:14 UTC, corverroos commented on lib/contracts/proxyadmin/deploy.go
> +		ExpectedAddr:   eoa.DevnetProxyAdmin(),
DevnetProxyAdmin is a contract, not a eoa

2024-04-18 11:06 UTC, corverroos commented on e2e/app/fund.go
>  		}
you currently have two ways to access an eoa address, lets align on only a single way, I suggest: `eoa.MustAddress(netconf.Staging, eoa.RoleRelayer)`

2024-04-18 11:06 UTC, corverroos commented on e2e/cmd/cmd.go
> +		eoaRole := eoa.Role(cfg.Name)
you still don't check that the eoa type==secret

2024-04-18 15:58 UTC, corverroos approved these changes

2024-04-18 15:58 UTC, corverroos commented on e2e/app/fund.go
> +			eoa.MustAddress(netconf.Staging, eoa.RoleFbDev),
lets reduce some duplication:
```
return eoa.MustAddresses(netconf.Staging, eao.AllRoles()...)
```

2024-04-18 16:09 UTC, merged